{% set name = "s2n" %}
{% set version = "0.10.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 25981f74908afe1bedeb10964b72fc07dbdfa700cb5b22cce0cf1d29d1ad92ac

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("s2n", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - ninja
  host:
    - openssl

test:
  commands:
    - test -f $PREFIX/lib/libs2n${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/s2n.h  # [unix]

about:
  home: https://github.com/awslabs/s2n
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: an implementation of the TLS/SSL protocols

extra:
  recipe-maintainers:
    - xhochy
